### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by ZKluv** [Gsllchb/Handright#39]
Traceback (most recent call last):
  File "k:\python\handwrite\main.py", line 8, in <module>
    font=ImageFont.truetype("font.ttf", size=100),
  File "C:\Users\ZK\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 878, in truetype     
    return freetype(font)
  File "C:\Users\ZK\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 875, in freetype     
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\ZK\AppData\Local\Programs\Python\Python310\lib\site-packages\PIL\ImageFont.py", line 226, in __init__     
    self.font = core.getfont(
OSError: cannot open resource

按照指示后，为什么会有OSError

**Comment by ZKluv** [comment]
麻烦帮忙看一下
